var CMS_ADMIN_MST_SQL={
    insert:'INSERT INTO CMS_ADMIN_MST (LOGIN_ID,PASSWORD,USER_NAME,POSITION,PERMISSIONS,MARK,CMP_TYPE) VALUES(?,?,?,?,?,?,?)',
    queryAll:'SELECT * FROM CMS_ADMIN_MST',
    getById:'SELECT * FROM CMS_ADMIN_MST WHERE ID=?',
    updateById:'UPDATE CMS_ADMIN_MST SET LOGIN_ID=?,PASSWORD=?,USER_NAME=?,POSITION=?,PERMISSIONS=?,MARK=?,CMP_TYPE=? WHERE ID=?',
    deleteById:'DELETE FROM CMS_ADMIN_MST WHERE ID=?',
}
module.exports=CMS_ADMIN_MST_SQL;

