var CMS_CODE_MST={
    insert:'INSERT INTO CMS_CODE_MST (CODE_ID,CODE_NAME,CODE_TYPE,CODE_VALUE1,CODE_VALUE2,CODE_VALUE3) VALUES(?,?,?,?,?,?)',
    queryAll:'SELECT * FROM CMS_CODE_MST',
    getById:'SELECT * FROM CMS_CODE_MST WHERE ID=?',
    getByCodeId:'SELECT * FROM CMS_CODE_MST WHERE CODE_ID=?',
    updateById:'UPDATE CMS_CODE_MST SET CODE_ID=?,CODE_NAME=?,CODE_TYPE=?,CODE_VALUE1=?,CODE_VALUE2=?,CODE_VALUE3=?WHERE ID=?',
    deleteById:'DELETE FROM CMS_CODE_MST WHERE ID=?',
}
module.exports=CMS_CODE_MST;